# Generated by Django 2.2.6 on 2019-10-28 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('content', models.TimeField()),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('receiver', models.ManyToManyField(related_name='ManyToMany', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ManyToOne', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
