# Generated by Django 2.2.6 on 2019-11-11 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=64)),
                ('section', models.CharField(max_length=64)),
                ('card_number', models.IntegerField(verbose_name='Id lekarza')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='zabieg', max_length=255, verbose_name='Nazwa')),
                ('description', models.TextField(verbose_name='Opis')),
                ('min_time', models.FloatField(verbose_name='Czas trwania zabiegu')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitalization_case', models.CharField(max_length=128, verbose_name='Powód hospitalizacji')),
                ('start_date', models.DateField(verbose_name='Data przyjęcia')),
                ('dr_description', models.TextField(verbose_name='Opis')),
                ('main_dr', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='interventions.Doctor', verbose_name='Lekarz prowadzący')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data operacji')),
                ('time', models.TimeField(verbose_name='Godzina operacji')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interventions.Doctor', verbose_name='Lekarz')),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interventions.Intervention', verbose_name='Zabieg')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interventions.Patient')),
            ],
        ),
    ]
