# Generated by Django 2.2.6 on 2019-10-29 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interventions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=64)),
                ('section', models.CharField(max_length=64)),
                ('card_number', models.IntegerField(verbose_name='Id lekarza')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='main_dr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='interventions.Doctor'),
        ),
    ]
